name: Compile Library
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Get iOS SDK
        run: |
          git clone --depth 1 https://github.com/theos/sdks.git sdks

      - name: Compile with Clang
        run: |
          mkdir -p output
          SDK_PATH=$(ls -d sdks/iPhoneOS*.sdk | head -n 1)
          
          xcrun --sdk iphoneos clang++ -arch arm64 \
            -dynamiclib \
            -isysroot "$SDK_PATH" \
            -miphoneos-version-min=14.0 \
            -framework Foundation \
            -framework UIKit \
            Tweak.cpp \
            -o output/SeedCatcher.dylib

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SeedCatcher_Dylib
          path: output/SeedCatcher.dylib
